### ISSUE TITLE
作者能考虑适配一下安卓吗 

### ISSUE THREAD

**Issue by CaiNiao0** [u0x01/bluedhook#1]
我可以配合

**Comment by u0x01** [comment]
> 我可以配合

GitHub 中有安卓版本

**Comment by CaiNiao0** [comment]
有个版本停更了，有个不适配新版 只有防闪图

**Comment by u0x01** [comment]
> 有个版本停更了，有个不适配新版 只有防闪图

我不太清楚 xposed 插件的实现，暂时没有时间学习这块，感兴趣的话可以自行研究下。
